### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by Mateoust** [yumenaka/comi#17]
**首先非常感谢大佬的付出。使用过程中发现有一些需要打磨的地方。以下我的一些想法**

 - 1.希望可以增加章节跳转按钮、例如观看一部超过500章节的漫画时。返回后总会退出到章节列表并回到第一话的位置。这样还需要往下翻动。会无形花费过多时间去重复跳转。
 - 2.增加一个章节列表的滚动记录。在看完某个章节返回后。会记录当前看到XXX话的位置。或者底部列表的方式？
 - 3.增加历史记录功能，这个可能需要一个api

以上是卷轴模式。翻页模式貌似有保存进度的功能。不过卷轴没有。希望能优化一下。
在翻页模式下，进度条在手机的画面比例时。进度条貌似在80%的比例，整体显得有些怪（阴影异常？）

**Comment by yumenaka** [comment]
好的，这些部分正好也在想办法优化。

1、卷轴模式会加分页，也在做阅读记录与恢复功能，阅读记录会存在浏览器+数据库中。
2、章节列表，或许可以通过改变书架展示方式来解决（类似详细信息列表的展示方式？）。
3、翻页界面正在重做，看来还需要多测一下手机上的效果。

**Comment by yumenaka** [comment]
0.9.7有章节跳转功能了。
翻页模式好久没看了，可能会用react重做。
