### ISSUE TITLE
Linux_x86_64 无法运行

### ISSUE THREAD

**Issue by Ukenn2112** [yumenaka/comi#18]
- 使用版本：[comi_v0.8.9_Linux_x86_64.tar.gz](https://github.com/yumenaka/comi/releases/download/v0.8.9/comi_v0.8.9_Linux_x86_64.tar.gz)

- 在运行 `comi --help` 时发生错误

- 系统版本 `Ubuntu 20.04.3 LTS x86_64`

- 控制台报错：
  ```shell
  panic: runtime error: index out of range [1] with length 1
  
  goroutine 1 [running]:
  github.com/yumenaka/comi/locale.getLocale()
          D:/cvgo/locale/localization.go:64 +0xeb
  github.com/yumenaka/comi/locale.init.0()
          D:/cvgo/locale/localization.go:92 +0x17f
  ```

貌似出现了windows路径？

**Comment by yumenaka** [comment]
看了一下代码，知道错误在哪儿了。
locale是 C.UTF-8 的时候，会导致数组越界出错。这个错误，也用WSL的Ubuntu重现了。

现在已经改掉BUG，重新编译了0.8.9版，Releases文件已替换，你可以下载试试。

**Comment by Ukenn2112** [comment]
谢谢，问题已解决～
