### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by leaim** [yumenaka/comi#21]
书架上增添漫画，可以增加用添加目录扫描的方式吗？
这样不用上传多一份，改变之前的存储结构。
还有一个就是双拼的漫画，需要一个切开的功能。
（顺带问问，速写功能是做什么用的
其他没什么问题了，完成度好高。

**Comment by yumenaka** [comment]
添加目录扫描：目录监视与动态添加，确实很实用，OK。
双拼漫画切单页：难度不大，可以做。计划在服务端转换，比较消耗CPU，低性能设备可能较慢（类似切白边）。
速写功能：我在练速写，所以需要定时翻页功能作参考。估计除了作者以外没几个人用，一般用户无视即可。

**Comment by yumenaka** [comment]
0.9.7可以添加目录扫描了，左上角服务器配置。
