### ISSUE TITLE
[Bug] panic: message "MIN_MEDIA_NUM" not found in language "ja-JP"

### ISSUE THREAD

**Issue by souvenp** [yumenaka/comi#25]
> panic: message "MIN_MEDIA_NUM" not found in language "ja-JP"
> 
> goroutine 1 [running]:
> github.com/nicksnyder/go-i18n/v2/i18n.(*Localizer).MustLocalize(0xc000090e80?, 0x1b?)
>         /Users/bai/soft/gopath/pkg/mod/github.com/nicksnyder/go-i18n/v2@v2.2.1/i18n/localizer.go:220 +0x3a
> github.com/yumenaka/comi/locale.GetString(...)
>         /Users/bai/cvgo/locale/localization.go:117
> github.com/yumenaka/comi/cmd.init.1()
>         /Users/bai/cvgo/cmd/root.go:61 +0x8af
> 
原本我的区域是日本，改成了中国就能正常了，很奇怪一开始我还好奇为什么拖过去没用🤔

**Comment by yumenaka** [comment]
谢谢反馈。

看了一下代码，日语翻译文件搞错了大小写,，所以在日语环境出错。  
代码已经改好了，下一个版本修复(正在做登录与配置重载，各种配置与功能做了一半，不适合发版)。

有go环境的话，可以试试这样从源代码安装：
go clone https://github.com/yumenaka/comi
cd comi
go install

**Comment by souvenp** [comment]
话说可不可以考虑加一个设置，一次性加载全部或者提前加载前后几张，对于大图会体验好一点

**Comment by yumenaka** [comment]
目前懒加载设定是固定值，图大的时候可能来不及加载。
1.0版会重构网页端，到时候把这一项也做成自定义项吧。
