### ISSUE TITLE
关于系统path

### ISSUE THREAD

**Issue by Ariacha** [yumenaka/comi#29]
我将文件夹目录放到系统path中，成功启动了，但是并不会扫描执行文件夹里面的config.toml文件，反而自动扫描了我的c盘所有图片（执行目录我放在d盘）请问这是什么原因

**Comment by yumenaka** [comment]
看了一下代码，当前的设置目录，是系统Home目录+执行目录。

就是没用配置文件的时候，第一句CMD提示 Config File "config.toml" Not Found in  "[/you/home/.config/comigo   /abc//Downloads]"  的两个路径。

好久没用windows了，扫描C盘，大概是因为CMD和 PowerShell 默认的启动位置，是C盘的用户个人主目录吧。CD到D盘才能扫D盘。

可能以前加过“可执行文件所在路径”这个配置文件位置，后来不知道哪次清理给改没了。

确实对windows用户来说，设置和可执行文件一起走最方便。

下个版本补上这个目录，然后在Windows下面也测一测。
