### ISSUE TITLE
问题与功能

### ISSUE THREAD

**Issue by maijz128** [yumenaka/comi#33]
问题：
1、网页修改服务器配置不会保存。（开箱即用原则，最好默认保存配置文件到本地）
2、文件夹名称显示不全，如：文件夹名称为“#海贼王”会显示为“海贼王”。

功能：
点击空白背景，返回上一层目录。

**Comment by yumenaka** [comment]
1 确实没做完。烦恼设置文件存在那个目录的时候，看到早期代码写的太烂就跑去重构了。为了方便CLI使用，应该会做的可以选择配置文件位置，存在当前执行目录或全局生效的home目录什么的。

2 我去试试。另外也应该可能因为前端默认开启【简化书名】功能，省略了了特殊符号与附加信息字符，类似[作者名]（出版日期）等等。

3 左上角的返回按钮，在手机上确实不好操作。空白感觉容易误触，考虑在底部加个浮动按钮。

**Comment by yumenaka** [comment]
服务器配置保存，0.9.7已完成。
