### ISSUE TITLE
希望可以添加点击屏幕弹出选择章数弹窗

### ISSUE THREAD

**Issue by bxiaob** [yumenaka/comi#34]
目前对于手机端浏览器只有顶部和底部可以选择章数，对于条漫来说，需要一直滑动到底部才可以选择章数，希望有时间可以优化移动端的体验，亦可以在阅读器设定中添加章数下拉框

**Comment by yumenaka** [comment]
好的。
反正接口是现成的，难度不大。

**Comment by yumenaka** [comment]
v0.9.7添加了快速跳转。
