### ISSUE TITLE
MacOS 无法上传 上传列表一直是红字

### ISSUE THREAD

**Issue by totono0721** [yumenaka/comi#37]
![image](https://github.com/yumenaka/comi/assets/50393231/80d03179-0881-499b-a0bc-bf8d1f303780)

**Comment by yumenaka** [comment]
谢谢报告BUG。

确认是发现上传成功后，重新扫描文件有问题。
另外上传成功的提示，也有点不明显。会在这几天修正。

**Comment by yumenaka** [comment]
https://github.com/yumenaka/comi/releases/tag/v0.9.8beta2

v0.9.8beta2修复。
感觉扫描文件的逻辑，需要好好整理一下了。
